language: python
sudo: false
dist: trusty

python:
  - 3.6

matrix:
  fast_finish: true

before_install:

script:
  - make build

deploy:
  provider: releases
  api_key:
    secure: nAET8iUc0xRrgVcovYKlVtSFQ1v8X7bTZlzqZiEj6cQIP4JYZgBTXcgSB7m3YkoqNStcgGdA2j0zCVIcq9fl1tgXg+qtyIDdCaWvTT+4oNb3aqkt57ZBZjIrqaHPYWnHK8chyT0kyOVSCe3nYRtCsXHY17f5CGlg50onQx6uTyM14ECIH4x+ubp4GKRTWS6eBd/59vsY3LbkgAjYabbmAHmGpTsPWT5GQb+EXl7/lCJlNudatrTHvrPXj2Ob1AXvJ/HYBkG/1BGZ91+2HXkuGaZxEqbyULKYose5gG3DWuPXjUqhqQapnOf7Lnb/gBtOfSyRsj2p8YBT3gWQQDTrOtHYVNh3jw5RGzkd89x09cml9nL/3jJ1L/tD9Uz+vVhV8UWS3jDFZ4kvKAlKT8/LV6pbJmYTGwwPHiq3TxaYfhQc3+qE55QzEazCnA0qPS7ReXt3K17hcHkwB2fjion89dLUC3CkEoq7P4LB4+Gf5043U4ik68HzT9NeHwLe8wn338Fg8jUxySP6SML8cALOHvHcQu3Zbxkd8rhPtryDnfFGs9UJCmshk3o8t8NiAbXyoDhuL7XyHXeyWdZge325/VTa64Hozp5PIfFy3ELQ1KoE6XANVRsgRxAQeeZaITgXLQMBXG4/O9GDDsoEqslt+CS/dxHNrtUEt/AaNuRh1BE=
  file:
    - data/timegeopack.sqlite3.zip
    - data/cities/timegeopack.topcities.zip
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: true
